WITH PARENT_TABLE AS (
    SELECT ID FROM ECOLI_DATA
    WHERE PARENT_ID in (
        SELECT ID FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    )
)

SELECT ID FROM ECOLI_DATA 
WHERE PARENT_ID in (
    SELECT ID FROM PARENT_TABLE
)
ORDER BY ID