Select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, 
USER_ID, SALES_AMOUNT 
FROM
(
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
    From ONLINE_SALE
    Where DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

    UNION ALL

    SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT  
    From OFFLINE_SALE 
    Where DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
) Q
Order By SALES_DATE, PRODUCT_ID, USER_ID