WITH 
## 할인율
DISCOUNT AS (
SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE DURATION_TYPE = '30일 이상'    
),
## 렌트 가능 차량
RENTAL AS (
SELECT * FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' 
        AND END_DATE >= '2022-11-01'
    )
)

SELECT * FROM (
    SELECT A.CAR_ID, A.CAR_TYPE, 
    ROUND((A.DAILY_FEE * (1 - (C.DISCOUNT_RATE * 0.01)) * 30)) FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN RENTAL B ON A.CAR_ID = B.CAR_ID
    JOIN DISCOUNT C ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_TYPE in ('SUV', '세단')
) Q

WHERE FEE >= 500000 and FEE < 2000000
ORDER BY FEE desc, CAR_TYPE, CAR_ID desc