-- 코드를 입력하세요
Select A.FOOD_TYPE, B.REST_ID, B.REST_NAME, A.FAVORITES
From (
    SELECT FOOD_TYPE, MAX(FAVORITES) As FAVORITES
    FROM REST_INFO 
    Group By FOOD_TYPE
) A 
Inner Join REST_INFO B On A.FOOD_TYPE = B.FOOD_TYPE and A.FAVORITES = B.FAVORITES
Order By A.FOOD_TYPE desc
