-- 코드를 입력하세요

SELECT 
    C.USER_ID, 
    C.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소,
    CONCAT(SUBSTRING(TLNO, 1, 3),'-',SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER C 
INNER JOIN (
SELECT USER_ID FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY USER_ID
HAVING COUNT(*) > 2
) D ON C.USER_ID = D.USER_ID
ORDER BY C.USER_ID DESC