SELECT YEAR, MONTH, GENDER, COUNT(*) USERS FROM (
SELECT A.USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, B.GENDER 
FROM ONLINE_SALE A
INNER JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER is not null
GROUP BY A.USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE), B.GENDER

) Q
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER