SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, B.GENDER, COUNT(distinct A.USER_ID) USERS
FROM ONLINE_SALE A
INNER JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER is not null
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), B.GENDER
ORDER BY YEAR, MONTH, GENDER

