WITH GRADE AS (
    SELECT EMP_NO, (SUM(SCORE) / 2) SCORE FROM HR_GRADE 
    GROUP BY EMP_NO
)

SELECT A.EMP_NO, A.EMP_NAME,
    (CASE 
        WHEN SCORE >= 96 THEN "S" 
        WHEN SCORE >= 90 THEN "A"
        WHEN SCORE >= 80 THEN "B" 
        ELSE "C" 
     END) GRADE,
    (CASE 
        WHEN SCORE >= 96 THEN SAL * 0.2 
        WHEN SCORE >= 90 THEN SAL * 0.15
        WHEN SCORE >= 80 THEN SAL * 0.1 
        ELSE 0 
     END) BONUS
FROM HR_EMPLOYEES A
JOIN GRADE B ON A.EMP_NO = B.EMP_NO