WITH MAX_MEMBER_ID AS (
    SELECT * FROM (
        SELECT MEMBER_ID, COUNT(*) cnt FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY cnt desc
    ) A
    LIMIT 1 
)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, 
    DATE_FORMAT(B.REVIEW_DATE , '%Y-%m-%d') REVIEW_DATE 
FROM MEMBER_PROFILE A
INNER JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID in (SELECT MEMBER_ID FROM MAX_MEMBER_ID)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT 
