WITH CAR_INFO AS (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(*) > 4
)

SELECT MONTH(START_DATE), A.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN CAR_INFO B ON A.CAR_ID = B.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY MONTH(START_DATE), A.CAR_ID
ORDER BY 1, 2 desc