WITH HR_GRADE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
    ORDER BY SCORE desc
    LIMIT 1
)

SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A
INNER JOIN HR_GRADE_SUM B ON A.EMP_NO = B.EMP_NO



