-- 코드를 입력하세요
Select A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID,
    B.CONTENTS, DATE_FORMAT(B.CREATED_DATE , '%Y-%m-%d') As CREATED_DATE
From USED_GOODS_BOARD A
    INNER Join USED_GOODS_REPLY B On A.BOARD_ID = B.BOARD_ID
Where A.CREATED_DATE BETWEEN '2022-10-01 00:00:00' and '2022-10-31 23:59:59'
Order By B.CREATED_DATE, A.TITLE