SELECT A.DEPT_ID, A.DEPT_NAME_EN, ROUND(B.SAL / B.cnt, 0) AVG_SAL
FROM HR_DEPARTMENT A
JOIN (
    SELECT DEPT_ID, COUNT(*) cnt, SUM(SAL) SAL FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) B ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID, A.DEPT_NAME_EN
ORDER BY AVG_SAL desc