SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
INNER JOIN 
(
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE FROM FOOD_PRODUCT
    WHERE CATEGORY in ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) B ON A.CATEGORY = B.CATEGORY and A.PRICE = B.MAX_PRICE
ORDER BY PRICE DESC